import type { InsertProduct } from "../drizzle/schema";

/**
 * Product seed data for Cloud Nine e-commerce
 * Based on specifications from requirements document
 */
export const productSeedData: Omit<InsertProduct, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "久留米絣ショルダー",
    slug: "kurume-kasuri-shoulder",
    description: "毎日使える、軽やかな久留米絣のショルダーバッグ。手仕事ならではの温かみと、使い込むほどに増す味わい。",
    price: 6000,
    category: "bags",
    priceRange: "5000-10000",
    madeToOrder: 0,
    featured: 1,
    bestSeller: 1,
    images: JSON.stringify(["/products/shoulder-1.jpg"]),
    dimensions: "幅 25cm × 高さ 20cm × マチ 8cm",
    material: "久留米絣（綿100%）、本革ストラップ",
    sortOrder: 1,
  },
  {
    name: "横長ショルダー（大）",
    slug: "wide-shoulder-large",
    description: "職人が一つひとつ丁寧に作り上げる、プレミアムコレクション。世界に一つだけの表情を持つ、久留米絣の逸品。",
    price: 10000,
    category: "bags",
    priceRange: "premium",
    madeToOrder: 1,
    featured: 1,
    bestSeller: 0,
    images: JSON.stringify(["/products/wide-large-1.jpg"]),
    dimensions: "幅 35cm × 高さ 25cm × マチ 10cm",
    material: "久留米絣（綿100%）、本革ストラップ",
    sortOrder: 2,
  },
  {
    name: "ミニショルダー",
    slug: "mini-shoulder",
    description: "コンパクトで使いやすい、ミニサイズのショルダーバッグ。ちょっとしたお出かけに最適です。",
    price: 7500,
    category: "bags",
    priceRange: "5000-10000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 1,
    images: JSON.stringify(["/products/mini-shoulder-1.jpg"]),
    dimensions: "幅 18cm × 高さ 15cm × マチ 5cm",
    material: "久留米絣（綿100%）、本革ストラップ",
    sortOrder: 3,
  },
  {
    name: "スマホ入れ",
    slug: "phone-case",
    description: "スマートフォンがぴったり入る、便利なポーチ。首から下げても、バッグに入れても。",
    price: 5400,
    category: "accessories",
    priceRange: "5000-10000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/phone-case-1.jpg"]),
    dimensions: "幅 10cm × 高さ 17cm",
    material: "久留米絣（綿100%）",
    sortOrder: 4,
  },
  {
    name: "ハンカチ",
    slug: "handkerchief",
    description: "毎日使える、久留米絣のハンカチ。伝統的な藍染めの美しさを日常に。",
    price: 3920,
    category: "textiles",
    priceRange: "under-5000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 1,
    images: JSON.stringify(["/products/handkerchief-1.jpg"]),
    dimensions: "45cm × 45cm",
    material: "久留米絣（綿100%）",
    sortOrder: 5,
  },
  {
    name: "横長ショルダー（中）",
    slug: "wide-shoulder-medium",
    description: "使いやすいサイズの横長ショルダー。普段使いにぴったりです。",
    price: 4600,
    category: "bags",
    priceRange: "under-5000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/wide-medium-1.jpg"]),
    dimensions: "幅 28cm × 高さ 20cm × マチ 7cm",
    material: "久留米絣（綿100%）、本革ストラップ",
    sortOrder: 6,
  },
  {
    name: "トートバッグ",
    slug: "tote-bag",
    description: "軽くて丈夫な、久留米絣のトートバッグ。お買い物やちょっとしたお出かけに。",
    price: 1500,
    category: "bags",
    priceRange: "under-5000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 1,
    images: JSON.stringify(["/products/tote-1.jpg"]),
    dimensions: "幅 35cm × 高さ 40cm × マチ 10cm",
    material: "久留米絣（綿100%）",
    sortOrder: 7,
  },
  {
    name: "ふでばこ",
    slug: "pencil-case",
    description: "文房具をすっきり収納できる、久留米絣のペンケース。学生から大人まで。",
    price: 4500,
    category: "accessories",
    priceRange: "under-5000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/pencil-case-1.jpg"]),
    dimensions: "幅 20cm × 高さ 8cm × マチ 5cm",
    material: "久留米絣（綿100%）、YKKファスナー",
    sortOrder: 8,
  },
  {
    name: "ハンカチ（小・ポケット）",
    slug: "handkerchief-pocket",
    description: "ポケットに入れやすい、小さめサイズのハンカチ。さりげなく久留米絣を楽しめます。",
    price: 5000,
    category: "textiles",
    priceRange: "5000-10000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/handkerchief-small-1.jpg"]),
    dimensions: "30cm × 30cm",
    material: "久留米絣（綿100%）",
    sortOrder: 9,
  },
  {
    name: "キーホルダー",
    slug: "keychain",
    description: "大切な方への贈り物に。200年続く伝統の技で織り上げた、特別な一点。",
    price: 10000,
    category: "accessories",
    priceRange: "premium",
    madeToOrder: 1,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/keychain-1.jpg"]),
    dimensions: "長さ 10cm",
    material: "久留米絣（綿100%）、真鍮金具",
    sortOrder: 10,
  },
  {
    name: "スタンプ（大）",
    slug: "stamp-large",
    description: "馬を愛する人のために。伝統工芸と乗馬ライフスタイルが出会う、特別なアイテム。",
    price: 30000,
    category: "special",
    priceRange: "premium",
    madeToOrder: 1,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/stamp-large-1.jpg"]),
    dimensions: "直径 8cm",
    material: "久留米絣、木製台座",
    sortOrder: 11,
  },
  {
    name: "スタンプ（中）",
    slug: "stamp-medium",
    description: "手仕事ならではの個性を持つ、久留米絣のスタンプ。一つひとつ表情が異なります。",
    price: 30000,
    category: "special",
    priceRange: "premium",
    madeToOrder: 1,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/stamp-medium-1.jpg"]),
    dimensions: "直径 6cm",
    material: "久留米絣、木製台座",
    sortOrder: 12,
  },
  {
    name: "スタンプ（小）",
    slug: "stamp-small",
    description: "小さくても存在感のある、久留米絣のスタンプ。手紙や書類に特別な印を。",
    price: 30000,
    category: "special",
    priceRange: "premium",
    madeToOrder: 1,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/stamp-small-1.jpg"]),
    dimensions: "直径 4cm",
    material: "久留米絣、木製台座",
    sortOrder: 13,
  },
  {
    name: "ワッペン",
    slug: "patch",
    description: "バッグや服に付けて楽しめる、久留米絣のワッペン。さりげないアクセントに。",
    price: 2800,
    category: "textiles",
    priceRange: "under-5000",
    madeToOrder: 0,
    featured: 0,
    bestSeller: 0,
    images: JSON.stringify(["/products/patch-1.jpg"]),
    dimensions: "直径 5cm",
    material: "久留米絣（綿100%）、アイロン接着",
    sortOrder: 14,
  },
];
